// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL8--yYc1Gc0gsfoQnD-WHZIrgoNOhElc',
    appId: '1:715434546649:web:a6b53dafa41627a31e75c8',
    messagingSenderId: '715434546649',
    projectId: 'login-1fe44',
    authDomain: 'login-1fe44.firebaseapp.com',
    storageBucket: 'login-1fe44.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC8xVxP1jbP2hbUhHPEk_S3HXZ-v5OnEE',
    appId: '1:715434546649:android:1974594546aeea241e75c8',
    messagingSenderId: '715434546649',
    projectId: 'login-1fe44',
    storageBucket: 'login-1fe44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgi-huL_S5lmPKNvNkzqmq-lBRcSVGz-8',
    appId: '1:715434546649:ios:150c95729a36cd0b1e75c8',
    messagingSenderId: '715434546649',
    projectId: 'login-1fe44',
    storageBucket: 'login-1fe44.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );
}
